#!/usr/bin/env bash
# Drift gate: the CSS property section embedded in
# documentation/compatibility-matrix.md must match the section regenerated by
# `python3 scripts/css-catalog-map.py --matrix`. Read-only; exits non-zero
# with a short diff when the embedded copy is stale.
set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)

cd "$repo_root"

matrix_file=documentation/compatibility-matrix.md

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

generated="$workdir/generated.md"
embedded="$workdir/embedded.md"
diff_out="$workdir/diff.txt"

# Regenerate the property section from testdata/css/catalog/properties.json.
if ! python3 scripts/css-catalog-map.py --matrix > "$generated"; then
  echo "matrix-sync: 'python3 scripts/css-catalog-map.py --matrix' failed" >&2
  exit 1
fi

if ! grep -q '^## 3\.' "$matrix_file"; then
  echo "matrix-sync: no '## 3.' heading in $matrix_file; cannot bound section 2" >&2
  exit 1
fi

# Extract the embedded copy: from `## 2. Supported CSS properties` up to the
# next `## 3.` heading.
awk '
  /^## 2\. Supported CSS properties[[:space:]]*$/ { in_section = 1 }
  in_section && /^## 3\./ { exit }
  in_section { print }
' "$matrix_file" > "$embedded"

if [ ! -s "$embedded" ]; then
  echo "matrix-sync: '## 2. Supported CSS properties' not found in $matrix_file" >&2
  exit 1
fi

# The generated section is rstripped and ends at the last table row; the
# embedded copy keeps one blank line as the separator before `## 3.`. Drop at
# most one trailing blank line so that separator is not reported as drift.
awk 'NR > 1 { print prev } { prev = $0 } END { if (prev != "") print prev }' \
  "$embedded" > "$embedded.normalized"
mv "$embedded.normalized" "$embedded"

if diff -u \
    --label "$matrix_file (embedded section 2)" \
    --label "scripts/css-catalog-map.py --matrix" \
    "$embedded" "$generated" > "$diff_out"; then
  echo "matrix-sync: ok (section 2 matches python3 scripts/css-catalog-map.py --matrix)"
  exit 0
fi

echo "matrix-sync: section 2 drift in $matrix_file" >&2
head -n 40 "$diff_out" >&2
if [ "$(wc -l < "$diff_out")" -gt 40 ]; then
  echo "matrix-sync: (diff truncated at 40 lines)" >&2
fi
echo "matrix-sync: regenerate with 'python3 scripts/css-catalog-map.py --matrix' and paste over section 2" >&2
exit 1
